fengines:
    chans_per_packet: 32
    pcie64:
        0:
            inputs: [0, 2]
            gbes: ['100.100.102.20']
            source_port: 10000
            dts_lane_map: [8,9,6,7,10,11,1,0,4,5,3,2]
        1:
            inputs: [2, 4]
            gbes: ['100.100.102.21']
            source_port: 10000
            dts_lane_map: [8,9,2,3,10,11,4,5,0,1,6,7]
    pcie65:
        0:
            inputs: [4, 6]
            gbes: ['100.100.102.22']
            source_port: 10000
            dts_lane_map: [8,9,10,11,4,5,6,7,0,1,2,3]
        1:
            inputs: [6, 8]
            gbes: ['100.100.102.23']
            source_port: 10000
            dts_lane_map: [8,9,10,11,0,1,2,3,4,5,6,7]

xengines:
  arp:
    # cosmic-gpu-0
    100.100.102.100: 0xb8cef6a64188
    100.100.103.100: 0xb8cef6a64189
  chans:
    # cosmic-gpu-0
    100.100.103.100-10000: [0, 512]
