fengines:
    chans_per_packet: 32
    pcie0:
        0:
            inputs: [0, 2]
            gbes: ['100.100.102.20']
            source_port: 10000
        1:
            inputs: [2, 4]
            gbes: ['100.100.102.21']
            source_port: 10000

xengines:
  arp:
    # cosmic-gpu-0
    100.100.102.100: 0xb8cef6a64188
    100.100.103.100: 0xb8cef6a64189
  chans:
    # cosmic-gpu-0
    100.100.102.100-10000: [0, 512]
