fengines:
    chans_per_packet: 64
    dts_lane_map:
        - [0,1,3,2,4,5,7,6,8,9,11,10] # Default for pipeline ID 0
        - [0,1,3,2,8,9,10,11,4,5,7,6] # Default for pipeline ID 1
    pcie64:
        0:
            feng_ids: [0, 1]
            gbes: ['100.100.102.20']
            source_port: 10000
        1:
            feng_ids: [2, 3]
            gbes: ['100.100.102.21']
            source_port: 10000
            #dts_lane_map: [8,9,2,3,10,11,4,5,0,1,6,7] Override default if necessary
    pcie65:
        0:
            feng_ids: [4, 5]
            gbes: ['100.100.102.22']
            source_port: 10000
        1:
            feng_ids: [6, 7]
            gbes: ['100.100.102.23']
            source_port: 10000

xengines:
  arp:
    # cosmic-gpu-0
    100.100.102.100: 0xb8cef6a64188
    100.100.103.100: 0xb8cef6a64189
  chans:
    # cosmic-gpu-0
    100.100.103.100-10000: [0, 512]
